# ClearLagg configuration file

config-version: 5
clear-interval: 300
broadcast-interval: 15
update-notify: true

worlds:
  world:
    enable-auto-clear: true

notify-players:
  enable: true
  message: "All dropped items will be cleared in 299 seconds!"
  countdown: 299

clear-message: "§aItems cleared!"
broadcast-message: "§bThe items will be deleted in {time} seconds."
